context.objects = [
    { factory = adapter
      args = {
        factory.name = api.alsa.pcm.sink
        node.name = guacamole-speakers
        node.description = "Internal speakers"
        media.class = "Audio/Sink"
        api.alsa.path = "guacamole_quiet"
        api.alsa.disable-mmap = true
        api.alsa.period-size = 1024
        api.alsa.period-num = 3
        audio.format = S24_32LE
        audio.rate = 48000
        audio.channels = 2
        audio.position = [ FL FR ]
        node.pause-on-idle = true
        session.suspend-timeout-seconds = 2
      }
    }
]
